image: alpine/edge
packages:
  - go
sources:
  - https://github.com/yinjun1991/caldav-client-go
tasks:
  - build: |
      cd go-webdav
      go build -race -v ./...
  - test: |
      cd go-webdav
      go test -race -v ./...
  - gofmt: |
      cd go-webdav
      test -z $(gofmt -l .)
